### ISSUE TITLE
机器人回复消息时无法引用回复之前的消息

### ISSUE THREAD

**Issue by garyvalue** [SideCloudGroup/BetterForward#18]
https://core.telegram.org/bots/api#replyparameters

**Comment by pplulee** [comment]
请提供截图以进一步说明遇到的问题

**Comment by garyvalue** [comment]
![photo_2024-08-08_18-02-15](https://github.com/user-attachments/assets/7c9af4a9-36f9-430c-8c2d-588994ea1c0c)
![photo_2024-08-08_18-02-21](https://github.com/user-attachments/assets/3069604c-5f3a-41fd-83e5-a4cd65418bd9)

**Comment by pplulee** [comment]
你升级一下版本，这个功能是1.0.5的时候加的
https://github.com/SideCloudGroup/BetterForward/releases/tag/1.0.5

**Comment by garyvalue** [comment]
我前天已经升级到latest版本

`During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/telebot/__init__.py", line 1081, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/local/lib/python3.12/site-packages/telebot/__init__.py", line 1169, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/local/lib/python3.12/site-packages/telebot/__init__.py", line 1244, in __threaded_polling
    raise e
  File "/usr/local/lib/python3.12/site-packages/telebot/__init__.py", line 1205, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/usr/local/lib/python3.12/site-packages/telebot/util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "/usr/local/lib/python3.12/site-packages/telebot/util.py", line 93, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/telebot/__init__.py", line 675, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/telebot/__init__.py", line 647, in get_updates
    json_updates = apihelper.get_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/telebot/apihelper.py", line 327, in get_updates
    return _make_request(token, method_url, params=payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/telebot/apihelper.py", line 161, in _make_request
    result = _get_req_session().request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)

2024-08-08 06:28:07 [INFO] 收到来自888的消息，内容：哪个，类型：text
2024-08-08 08:12:05 [INFO] 收到来自999的消息，内容：1，类型：text
`

**Comment by pplulee** [comment]
1. 你日志中的报错是与telegram服务器通信出现问题导致的，偶尔出现这个报错正常
2. 新版本中在群组内看不到“转发”，消息是由bot直接发送的。如果看到的是转发的消息，就不是最新版本。但是你的日志是最新的版本。请检查有没有搞错bot

**Comment by garyvalue** [comment]
版本使用的是 pplulee/betterforward:latest

**Comment by pplulee** [comment]
docker ps和docker images截图看一下

**Comment by garyvalue** [comment]
十分抱歉。可能是镜像拉取失败，一直是旧版本镜像
重新拉取镜像后测试正常
非常抱歉，耽误你的时间
